# GitHub Actions CI/CD Workflow for Harmonix Pro Analyzer
# This is a template that should be placed in: .github/workflows/ci.yml

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'release/**'
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  NPM_CACHE_DIR: ~/.npm
  ARTIFACT_NAME: harmonix-build-${{ github.run_number }}

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write

jobs:
  # ============================================================================
  # STAGE 1: SETUP & LINT
  # ============================================================================
  setup-and-lint:
    name: Setup, Lint & Type Check
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # For changelog generation

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci --prefer-offline --no-audit

      - name: Run ESLint
        working-directory: frontend
        run: npm run lint
        continue-on-error: false

      - name: Run TypeScript compiler
        working-directory: frontend
        run: npm run typecheck
        continue-on-error: false

      - name: Cache build artifacts
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules
            frontend/.eslintcache
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  # ============================================================================
  # STAGE 2: SECURITY SCANNING
  # ============================================================================
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci --prefer-offline --no-audit

      - name: Run npm audit for vulnerabilities
        working-directory: frontend
        id: npm-audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Report npm audit results
        if: steps.npm-audit.outcome == 'failure'
        working-directory: frontend
        run: |
          echo "::error::Security vulnerabilities detected. Run 'npm audit' locally to review."
          npm audit --json > audit-report.json
          exit 1

      - name: Check for hardcoded secrets (optional)
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./frontend
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
        continue-on-error: true

      - name: SAST scan with Semgrep (optional)
        uses: returntocorp/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/owasp-top-ten
            p/cwe-top-25
          generateSarif: true
        continue-on-error: true

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: semgrep.sarif
        continue-on-error: true

  # ============================================================================
  # STAGE 3: UNIT TESTS
  # ============================================================================
  unit-tests:
    name: Unit Tests & Coverage
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: setup-and-lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci --prefer-offline --no-audit

      - name: Run unit tests with coverage
        working-directory: frontend
        run: |
          npm run test:unit -- \
            --coverage \
            --reporter=verbose \
            --reporter=json \
            --outputFile=coverage/test-results.json
        continue-on-error: true

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./frontend/coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: true

      - name: Check coverage thresholds
        working-directory: frontend
        run: |
          COVERAGE=$(cat coverage/coverage-final.json | grep -o '"lines":[^}]*' | grep -o '[0-9.]*' | head -1)
          MIN_COVERAGE=50
          echo "Current coverage: ${COVERAGE}%"
          if (( $(echo "$COVERAGE < $MIN_COVERAGE" | bc -l) )); then
            echo "::error::Coverage ${COVERAGE}% is below minimum ${MIN_COVERAGE}%"
            exit 1
          fi
        continue-on-error: true

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: |
            frontend/coverage/
            frontend/test-results/
          retention-days: 30

  # ============================================================================
  # STAGE 4: BUILD
  # ============================================================================
  build:
    name: Build Application
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [setup-and-lint, unit-tests, security-scan]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: frontend
        run: npm ci --prefer-offline --no-audit

      - name: Build application
        working-directory: frontend
        run: npm run build:prod
        env:
          NODE_ENV: production
          VITE_BUILD_TIME: ${{ github.event.head_commit.timestamp }}

      - name: Verify build artifacts
        working-directory: frontend
        run: |
          echo "Checking build output..."
          test -d dist || (echo "::error::dist directory not found"; exit 1)
          test -f dist/index.html || (echo "::error::index.html not found"; exit 1)
          echo "Build artifacts verified"

      - name: Check bundle size
        working-directory: frontend
        run: |
          BUNDLE_SIZE=$(du -sh dist/assets/js/*.js | tail -1 | awk '{print $1}')
          VENDOR_SIZE=$(ls -lh dist/assets/js/vendor*.js | awk '{print $5}')
          echo "Total JS bundle size: $BUNDLE_SIZE"
          echo "Vendor chunk size: $VENDOR_SIZE"

          # Set warnings (not hard limits for initial setup)
          echo "::notice::Bundle size check complete. Vendor: $VENDOR_SIZE"

      - name: Generate bundle analysis report
        working-directory: frontend
        run: npm run build:analyze > bundle-analysis.txt 2>&1
        continue-on-error: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            frontend/dist/
            frontend/bundle-analysis.txt
          retention-days: 30

      - name: Comment PR with build info
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            let comment = '## Build Report\n\n';
            comment += '✅ Build successful\n\n';

            // Check for bundle analysis
            if (fs.existsSync('frontend/bundle-analysis.txt')) {
              const analysis = fs.readFileSync('frontend/bundle-analysis.txt', 'utf8');
              comment += '### Bundle Analysis\n```\n' + analysis.slice(0, 500) + '...\n```\n';
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  # ============================================================================
  # STAGE 5: DOCKER BUILD (Optional)
  # ============================================================================
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: harmonix:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/image.tar

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{ github.run_number }}
          path: /tmp/image.tar
          retention-days: 7

  # ============================================================================
  # STAGE 6: DEPLOY TO STAGING (Optional, requires credentials)
  # ============================================================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build, docker-build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/main')
    environment:
      name: staging
      url: https://staging.harmonix.example.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: dist-artifacts

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Example: Deploy to Vercel
          # npx vercel --prod --token=${{ secrets.VERCEL_TOKEN }}

          # Or deploy to custom server via SSH
          # mkdir -p ~/.ssh
          # echo "${{ secrets.STAGING_SSH_KEY }}" > ~/.ssh/id_rsa
          # chmod 600 ~/.ssh/id_rsa
          # ssh -i ~/.ssh/id_rsa deploy@staging.example.com "cd /var/www/harmonix && bash deploy.sh"

          echo "Deployment complete"
        continue-on-error: true

      - name: Run smoke tests on staging
        run: |
          echo "Running smoke tests..."
          # curl -f https://staging.harmonix.example.com/ || exit 1
          # npm run test:smoke:staging
          echo "Smoke tests complete"
        continue-on-error: true

      - name: Notify deployment status
        if: always()
        run: |
          STATUS=${{ job.status }}
          echo "::notice::Staging deployment $STATUS"

  # ============================================================================
  # WORKFLOW STATUS
  # ============================================================================
  workflow-status:
    name: Workflow Status
    runs-on: ubuntu-latest
    needs: [setup-and-lint, unit-tests, security-scan, build]
    if: always()

    steps:
      - name: Check workflow status
        run: |
          echo "Pipeline Status Summary:"
          echo "- Lint & Type Check: ${{ needs.setup-and-lint.result }}"
          echo "- Unit Tests: ${{ needs.unit-tests.result }}"
          echo "- Security Scan: ${{ needs.security-scan.result }}"
          echo "- Build: ${{ needs.build.result }}"

          if [ "${{ needs.setup-and-lint.result }}" != "success" ]; then
            echo "::error::Lint/Type check failed"
            exit 1
          fi

          if [ "${{ needs.unit-tests.result }}" != "success" ]; then
            echo "::warning::Unit tests failed (non-blocking)"
          fi

          if [ "${{ needs.security-scan.result }}" == "failure" ]; then
            echo "::error::Security scan failed"
            exit 1
          fi

          if [ "${{ needs.build.result }}" != "success" ]; then
            echo "::error::Build failed"
            exit 1
          fi

          echo "::notice::Pipeline passed all required checks"

# ============================================================================
# MANUAL DEPLOYMENT WORKFLOWS (Separate files)
# ============================================================================
# These should be in separate workflow files:
# - .github/workflows/deploy-production.yml
# - .github/workflows/release.yml
# - .github/workflows/dependency-updates.yml

# ============================================================================
# NOTES
# ============================================================================
# 1. Secrets required:
#    - CODECOV_TOKEN (optional, for codecov.io)
#    - VERCEL_TOKEN (if using Vercel)
#    - STAGING_SSH_KEY (if using custom server)
#    - DOCKER_REGISTRY_USERNAME (if pushing to registry)
#    - DOCKER_REGISTRY_PASSWORD (if pushing to registry)
#
# 2. Required repository settings:
#    - Branch protection on main (require status checks)
#    - Require pull request reviews
#    - Require code review from code owners
#    - Require branches to be up to date before merging
#
# 3. Optional integrations:
#    - GitHub Code Scanning (CodeQL)
#    - Dependabot for automated updates
#    - Renovate as alternative
#    - CODEOWNERS file for PR routing
#
# 4. Performance optimizations:
#    - Node modules caching via actions/setup-node
#    - Docker layer caching via buildx
#    - Parallel job execution
#    - Job dependencies to prevent unnecessary runs
#
# 5. Troubleshooting:
#    - Check "Actions" tab in GitHub for workflow runs
#    - Review job logs for specific errors
#    - Use GitHub debug logging (secrets.ACTIONS_STEP_DEBUG)
