/**
 * PDF Export Utility
 * Generates professional PDF reports from analysis data
 * Uses a simple approach without external libraries for minimal bundle size
 */

import type { AudioAnalysisResult } from '../types/audio';

export interface PDFExportOptions {
  filename?: string;
  title?: string;
  includeMetadata?: boolean;
}

/**
 * Generate PDF report from analysis data
 * Uses HTML Canvas + window.print for PDF generation (no external libs needed)
 */
export async function exportToPDF(
  analysisData: AudioAnalysisResult,
  audioFilename: string,
  options: PDFExportOptions = {}
): Promise<void> {
  const {
    title = 'Audio Analysis Report',
    includeMetadata = true,
  } = options;

  // Create a hidden iframe for printing
  const iframe = document.createElement('iframe');
  iframe.style.position = 'absolute';
  iframe.style.width = '0';
  iframe.style.height = '0';
  iframe.style.border = 'none';
  document.body.appendChild(iframe);

  const iframeDoc = iframe.contentDocument || iframe.contentWindow?.document;
  if (!iframeDoc) {
    document.body.removeChild(iframe);
    throw new Error('Could not create PDF document');
  }

  // Generate HTML content
  const htmlContent = generatePDFHTML(analysisData, audioFilename, title, includeMetadata);

  iframeDoc.open();
  iframeDoc.write(htmlContent);
  iframeDoc.close();

  // Trigger print dialog
  setTimeout(() => {
    iframe.contentWindow?.print();

    // Clean up after a delay
    setTimeout(() => {
      document.body.removeChild(iframe);
    }, 1000);
  }, 500);
}

function generatePDFHTML(
  data: AudioAnalysisResult,
  filename: string,
  title: string,
  includeMetadata: boolean
): string {
  const now = new Date().toLocaleString();

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    @page {
      size: A4;
      margin: 2cm;
    }

    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      font-size: 11pt;
      line-height: 1.5;
      color: #1a1a1a;
      background: white;
      margin: 0;
      padding: 0;
    }

    .header {
      border-bottom: 3px solid #2563eb;
      padding-bottom: 1rem;
      margin-bottom: 2rem;
    }

    h1 {
      margin: 0;
      font-size: 24pt;
      color: #1e40af;
    }

    .subtitle {
      margin: 0.5rem 0 0 0;
      color: #64748b;
      font-size: 10pt;
    }

    .metadata {
      background: #f1f5f9;
      padding: 1rem;
      border-radius: 4px;
      margin-bottom: 2rem;
    }

    .metadata-row {
      display: flex;
      justify-content: space-between;
      margin: 0.5rem 0;
    }

    .metadata-label {
      font-weight: 600;
      color: #475569;
    }

    .section {
      margin-bottom: 2rem;
      page-break-inside: avoid;
    }

    .section-title {
      font-size: 14pt;
      font-weight: 600;
      color: #1e40af;
      border-bottom: 2px solid #e2e8f0;
      padding-bottom: 0.5rem;
      margin-bottom: 1rem;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 1rem;
    }

    th {
      background: #f1f5f9;
      padding: 0.75rem;
      text-align: left;
      font-weight: 600;
      border-bottom: 2px solid #cbd5e1;
    }

    td {
      padding: 0.75rem;
      border-bottom: 1px solid #e2e8f0;
    }

    .metric {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 1rem;
      margin-bottom: 1rem;
    }

    .metric-item {
      background: #f8fafc;
      padding: 1rem;
      border-left: 3px solid #3b82f6;
    }

    .metric-label {
      font-size: 9pt;
      color: #64748b;
      text-transform: uppercase;
      margin-bottom: 0.25rem;
    }

    .metric-value {
      font-size: 16pt;
      font-weight: 700;
      color: #1e293b;
    }

    .confidence {
      font-size: 9pt;
      color: #475569;
      margin-top: 0.25rem;
    }

    .footer {
      margin-top: 3rem;
      padding-top: 1rem;
      border-top: 1px solid #e2e8f0;
      text-align: center;
      color: #94a3b8;
      font-size: 9pt;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${title}</h1>
    <p class="subtitle">Generated by Harmonix Pro Analyzer</p>
  </div>

  ${includeMetadata ? `
  <div class="metadata">
    <div class="metadata-row">
      <span class="metadata-label">File:</span>
      <span>${filename}</span>
    </div>
    <div class="metadata-row">
      <span class="metadata-label">Analysis Date:</span>
      <span>${now}</span>
    </div>
    ${data.duration ? `
    <div class="metadata-row">
      <span class="metadata-label">Duration:</span>
      <span>${formatDuration(data.duration)}</span>
    </div>
    ` : ''}
  </div>
  ` : ''}

  ${data.tempo || data.key ? `
  <div class="section">
    <h2 class="section-title">Musical Analysis</h2>
    <div class="metric">
      ${data.tempo ? `
      <div class="metric-item">
        <div class="metric-label">Tempo (BPM)</div>
        <div class="metric-value">${data.tempo.bpm.toFixed(1)}</div>
        ${data.tempo.confidence ? `<div class="confidence">Confidence: ${(data.tempo.confidence * 100).toFixed(0)}%</div>` : ''}
      </div>
      ` : ''}
      ${data.key ? `
      <div class="metric-item">
        <div class="metric-label">Musical Key</div>
        <div class="metric-value">${data.key.key} ${data.key.scale}</div>
        ${data.key.confidence ? `<div class="confidence">Confidence: ${(data.key.confidence * 100).toFixed(0)}%</div>` : ''}
      </div>
      ` : ''}
    </div>
  </div>
  ` : ''}

  ${data.spectral ? `
  <div class="section">
    <h2 class="section-title">Spectral Features</h2>
    <table>
      <thead>
        <tr>
          <th>Feature</th>
          <th>Mean</th>
          <th>Std Dev</th>
        </tr>
      </thead>
      <tbody>
        ${Object.entries(data.spectral).map(([key, value]) => {
          if (value && typeof value === 'object' && 'mean' in value) {
            return `
            <tr>
              <td>${key.charAt(0).toUpperCase() + key.slice(1)}</td>
              <td>${value.mean?.toFixed(2) || 'N/A'}</td>
              <td>${value.std?.toFixed(2) || 'N/A'}</td>
            </tr>
            `;
          }
          return '';
        }).join('')}
      </tbody>
    </table>
  </div>
  ` : ''}

  ${data.mfcc && data.mfcc.length > 0 ? `
  <div class="section">
    <h2 class="section-title">MFCC Coefficients</h2>
    <table>
      <thead>
        <tr>
          <th>Coefficient</th>
          <th>Value</th>
        </tr>
      </thead>
      <tbody>
        ${data.mfcc.slice(0, 13).map((val, idx) => `
        <tr>
          <td>MFCC ${idx + 1}</td>
          <td>${val.toFixed(4)}</td>
        </tr>
        `).join('')}
      </tbody>
    </table>
  </div>
  ` : ''}

  ${data.loudness ? `
  <div class="section">
    <h2 class="section-title">Loudness Analysis</h2>
    <div class="metric">
      ${data.loudness.integrated !== undefined ? `
      <div class="metric-item">
        <div class="metric-label">Integrated Loudness</div>
        <div class="metric-value">${data.loudness.integrated.toFixed(1)} LUFS</div>
      </div>
      ` : ''}
      ${data.loudness.dynamicRange !== undefined ? `
      <div class="metric-item">
        <div class="metric-label">Dynamic Range</div>
        <div class="metric-value">${data.loudness.dynamicRange.toFixed(1)} LU</div>
      </div>
      ` : ''}
    </div>
  </div>
  ` : ''}

  <div class="footer">
    <p>Harmonix Pro Analyzer • Professional Music Analysis Tool</p>
  </div>
</body>
</html>
  `;
}

function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins}:${secs.toString().padStart(2, '0')}`;
}
